version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.X_BOT_ORG_REPO_ONLY_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    registries:
      - github-octocat
    schedule:
      interval: 

      time: ""
      timezone: ""
    open-pull-requests-limit: 99
