version: 2
registries:
  bnw-registry:
    type: rubygems-server
    url: https://bnw-registry.simplybusiness.io
    username: 
    password: 
  bnw-registry-npm:
    type: npm-registry
    url: https://bnw-registry.simplybusiness.io
    username: 
    password: 
updates:
  - package-ecosystem: bundler
    directory: /
    insecure-external-code-execution: allow
    registries:
      - bnw-registry
    schedule:
      interval: daily
      time: "07:30"
      timezone: "Europe/London"
    rebase-strategy: disabled
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: simplecov
        versions:
          - ">= 0.18"
      - dependency-name: rater
      - dependency-name: phoney
      - dependency-name: reform
      - dependency-name: sass-rails
      - dependency-name: snowplow_ruby_duid
      - dependency-name: react_on_rails_pro
      - dependency-name: jquery-ui-rails
      - dependency-name: zip-codes
    groups:
      aws-sdk:
        patterns:
          - "aws-sdk-*"
      sidekiq:
        patterns:
          - "sidekiq"
          - "sidekiq-ent"
          - "sidekiq-pro"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - bnw-registry-npm
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "@backstage*"
      - dependency-name: "@spotify/backstage*"
      - dependency-name: "@hey-api/*"
      - dependency-name: "@roadiehq/*"
      - dependency-name: "@dweber019/*"
      - dependency-name: "@janus-idp/*"
      - dependency-name: "@frontside/*"
      - dependency-name: "typescript"
    allow:
      - dependency-type: "direct"
    groups:
      prettier:
        patterns:
          - "prettier*"
          - "@prettier*"
      babel:
        patterns:
          - "babel*"
          - "@babel*"
      jest:
        patterns:
          - "jest*"
          - "@jest*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "@typescript-eslint/*"
      react-dependencies:
        patterns:
          - "react*"
      aws-dependencies:
        patterns:
          - "aws-*"
          - "@aws-sdk*"
      material-ui-dependencies:
        patterns:
          - "@mui/*"
          - "@material-table*"
      swc-dependencies:
        patterns:
          - "@swc/*"
      swagger-dependencies:
        patterns:
          - "@swagger-api/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 99
